version: '3.8'

services:
  web:
    build: .
    container_name: web_app
    ports:
      - "8000:8000"
    environment:
      # - MONGO_URI=${MONGO_URI}
      - MONGO_URI=mongodb://mongo:27017/web_app_db
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: